sudo: required
services:
  - docker
before_install:
  - docker build -t dstasaski/angular-test -f ./web/Dockerfile.dev ./web
script:
  - docker run dstasaski/angular-test npm run test -- --no-watch --no-progress --browsers=ChromiumNoSandbox 

