sudo: required
services:
  - docker

before_install:
  - docker build -t dstasaski/angular-test -f ./web/Dockerfile.dev ./web

script:
  - docker run dstasaski/angular-test npm run test -- --no-watch --no-progress --browsers=ChromiumNoSandbox 

after_success:
  - docker build -t dstasaski/tunetext-web ./web
  - docker build -t dstasaski/tunetext-api ./api
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_ID --password-stdin
  - docker push dstasaski/tunetext-web
  - docker push dstasaski/tunetext-api

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: tunetext
  env: Tunetext-env
  bucket_name: elasticbeanstalk-us-east-2-277856193737
  bucket_path: tunetext
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY

