version: '3'
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '8080:80'
  web:
    container_name: web
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    volumes:
      - './web:/app'
      - '/app/node_modules'
    ports:
      - '4200:4200'
    environment:
      - CHOKIDAR_USEPOLLING=true
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - './api:/app'
    ports:
      - '5000:5000'
    env_file:
      - api.env
