version: '3'
services:
  frontend:
    container_name: frontend
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    volumes:
      - './web:/app'
      - '/app/node_modules'
    ports:
      - '4200:4200'
    environment:
      - CHOKIDAR_USEPOLLING=true
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - './api:/app'
    ports:
      - '5000:5000'

